[package]
name = "server"
version.workspace = true
edition = "2024"

[dependencies]
axum = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
metrics = { workspace = true }