[package]
name = "utils"
version.workspace = true
edition = "2024"

[dependencies]
eyre = { workspace = true }
tracing.workspace = true
alloy.workspace = true
futures-util.workspace = true
bindings.workspace = true
metrics.workspace = true
tokio.workspace = true